### ISSUE TITLE
Why does this happen ?

### ISSUE THREAD

**Issue by Flonki** [facorazza/Passwords2Bitwarden#6] opened 2024-02-14 19:21 UTC
```
Traceback (most recent call last):
  File "C:\Users\Flonki\Documents\Test123\Passwords2Bitwarden\Passwords2Bitwarden-4-fails-if-there-are-no-favorite-passwords\main.py", line 78, in <module>
    cli()
  File "C:\Users\Flonki\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Flonki\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Flonki\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Flonki\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Flonki\Documents\Test123\Passwords2Bitwarden\Passwords2Bitwarden-4-fails-if-there-are-no-favorite-passwords\main.py", line 25, in cli
    if row["ParentLabel"] == "Home":
       ~~~^^^^^^^^^^^^^^^
KeyError: 'ParentLabel'
```

This Happens to me 
Can someone help me

**Comment by facorazza** [comment] 2024-02-14 19:37
For some reason the rows in your `Folders.csv` do not contain the `ParentLabel` key

**Comment by Flonki** [comment] 2024-02-14 21:06
Do you know how i can Fix that ?

**Comment by facorazza** [comment] 2024-02-14 21:17
Can you paste a few lines of your `Folders.csv`?

**Comment by Flonki** [comment] 2024-02-16 01:08
```
"Name","Überordner","Favorit","Bearbeitet am","Id","Version","Überordner Id"
"Test","Hauptordner","nein","Tue Apr 18 2023 13:14:46 GMT+0200 (Mitteleuropäische Sommerzeit)","bf860d0e-7276-4750-ac38-7b42d3asd80asd05cd","89dbaasdsdb2a4-e827-423a-94e5-87ad249ab76b","00000000-0000-0000-0000-000000000000"
"Server Pass","Hauptordner","nein","Tue Apr 18 2023 13:01:51 GMT+0200 (Mitteleuropäische Sommerzeit)","40234466-3183-4asada-9f22-06acda72cbb9","a9938f3c-6f87-4259-8eb3-46fae940f520","00000000-0000-0000-0000-000000000000"
"2","PixAI","nein","Tue Apr 18 2023 13:15:12 GMT+0200 (Mitteleuropäische Sommerzeit)","45f6763c-cb49-4cbe-81dsad8-6f9d154asd281f0","d1c9dasdc2-3df5-471c-be16-4asdf91e827f798","bf86asd0d0e-7276-4750-ac38-7b42asdd38005cd"
```
Here is the Whole thing i think i contains nothing which would be bad to leak

**Comment by facorazza** [comment] 2024-02-16 06:49
This is likely a duplicate of #1. You should switch the NC language to English before exporting as stated in the README

**Comment by facorazza** [comment] 2024-02-20 22:36
@Flonki Please close the issue if it's been solved

**Closed as completed** 2024-02-21 14:58 UTC
